import type { Question, Lesson } from "@/types";

/** 生化学 — 代謝と酵素（医師国家試験レベル） */
export const biochemistryQuestions: Question[] = [
  // ── Lesson 1: 代謝と酵素 ──────────────────────────────────────────────────
  {
    id: "q-bc-1-1",
    lessonId: "biochemistry-1",
    text: "解糖系（Embden-Meyerhof経路）の最終産物はどれか。",
    options: [
      { id: "a", text: "ピルビン酸" },
      { id: "b", text: "アセチルCoA" },
      { id: "c", text: "乳酸" },
      { id: "d", text: "オキサロ酢酸" },
    ],
    correctOptionId: "a",
    explanation:
      "解糖系はグルコース1分子を2分子のピルビン酸に分解し、正味2ATPと2NADHを産生する経路である。反応は細胞質（サイトゾル）で進行する。好気的条件下ではピルビン酸はミトコンドリアに入りピルビン酸デヒドロゲナーゼ複合体によりアセチルCoAに変換される。嫌気的条件下（激しい運動時の骨格筋や赤血球など）では乳酸デヒドロゲナーゼによりピルビン酸が乳酸に還元され、NAD⁺が再生される。アセチルCoAは解糖系の産物ではなくピルビン酸の酸化的脱炭酸の産物である。",
    subject: "生化学",
    order: 1,
  },
  {
    id: "q-bc-1-2",
    lessonId: "biochemistry-1",
    text: "TCA回路（クエン酸回路）が進行する細胞内の場所はどれか。",
    options: [
      { id: "a", text: "細胞質（サイトゾル）" },
      { id: "b", text: "ミトコンドリアマトリックス" },
      { id: "c", text: "ミトコンドリア内膜" },
      { id: "d", text: "小胞体" },
    ],
    correctOptionId: "b",
    explanation:
      "TCA回路（クエン酸回路・Krebs回路）はミトコンドリアマトリックスで進行する。アセチルCoAがオキサロ酢酸と縮合してクエン酸となり、8段階の酵素反応を経て再びオキサロ酢酸に戻る。1回転あたり3NADH・1FADH₂・1GTP（ATP相当）・2CO₂が生成される。ミトコンドリア内膜は電子伝達系の場であり、細胞質は解糖系の場である。TCA回路の酵素のうちコハク酸デヒドロゲナーゼ（複合体II）のみがミトコンドリア内膜に埋め込まれている点も国試で問われる。",
    subject: "生化学",
    order: 2,
  },
  {
    id: "q-bc-1-3",
    lessonId: "biochemistry-1",
    text: "電子伝達系において、最終的に電子を受け取る物質はどれか。",
    options: [
      { id: "a", text: "NAD⁺" },
      { id: "b", text: "FAD" },
      { id: "c", text: "酸素（O₂）" },
      { id: "d", text: "コエンザイムQ（ユビキノン）" },
    ],
    correctOptionId: "c",
    explanation:
      "電子伝達系はミトコンドリア内膜に存在する複合体I〜IVからなる。NADHやFADH₂から供給された電子は複合体I（またはII）→コエンザイムQ→複合体III→シトクロムc→複合体IVと順次受け渡され、最終電子受容体である酸素（O₂）に渡されてH₂Oが生成される。この過程でプロトン（H⁺）がマトリックスから膜間腔にくみ出され、プロトン濃度勾配が形成される。ATP合成酵素（複合体V）はこのプロトン勾配を利用してADPとPiからATPを合成する（酸化的リン酸化）。グルコース1分子あたり最大約30〜32ATPが産生される。",
    subject: "生化学",
    order: 3,
  },
  {
    id: "q-bc-1-4",
    lessonId: "biochemistry-1",
    text: "糖新生の律速酵素として正しいのはどれか。",
    options: [
      { id: "a", text: "ヘキソキナーゼ" },
      { id: "b", text: "ホスホフルクトキナーゼ-1（PFK-1）" },
      { id: "c", text: "ホスホエノールピルビン酸カルボキシキナーゼ（PEPCK）" },
      { id: "d", text: "ピルビン酸キナーゼ" },
    ],
    correctOptionId: "c",
    explanation:
      "糖新生は解糖系の逆反応であるが、解糖系の3つの不可逆反応を迂回する必要がある。その迂回酵素が①ピルビン酸カルボキシラーゼ＋ホスホエノールピルビン酸カルボキシキナーゼ（PEPCK）、②フルクトース-1,6-ビスホスファターゼ、③グルコース-6-ホスファターゼである。PEPCKは糖新生の律速酵素であり、グルカゴン・コルチゾールにより誘導され、インスリンにより抑制される。ヘキソキナーゼ・PFK-1・ピルビン酸キナーゼはいずれも解糖系の不可逆反応酵素（律速酵素）である。糖新生は主に肝臓と腎臓で行われ、絶食時の血糖維持に不可欠である。",
    subject: "生化学",
    order: 4,
  },
  {
    id: "q-bc-1-5",
    lessonId: "biochemistry-1",
    text: "脂肪酸のβ酸化について正しいのはどれか。",
    options: [
      { id: "a", text: "β酸化は細胞質（サイトゾル）で進行する" },
      { id: "b", text: "β酸化1サイクルごとにアセチルCoA・FADH₂・NADHが各1分子生成される" },
      { id: "c", text: "長鎖脂肪酸はそのままミトコンドリア内膜を通過できる" },
      { id: "d", text: "β酸化の律速酵素はアセチルCoAカルボキシラーゼである" },
    ],
    correctOptionId: "b",
    explanation:
      "脂肪酸のβ酸化はミトコンドリアマトリックスで進行する。1サイクル（酸化→水和→酸化→チオリシス）ごとに炭素鎖がC2短縮され、アセチルCoA 1分子・FADH₂ 1分子・NADH 1分子が産生される。長鎖脂肪酸（C12以上）はカルニチンシャトル（CPT-I → カルニチンアシルトランスフェラーゼ → CPT-II）を介してミトコンドリア内膜を通過する必要がある。CPT-Iがβ酸化の律速段階であり、マロニルCoAにより阻害される。アセチルCoAカルボキシラーゼは脂肪酸合成の律速酵素である。パルミチン酸（C16）のβ酸化では7サイクルで8アセチルCoA・7FADH₂・7NADHが生じ、合計約106ATPが産生される。",
    subject: "生化学",
    order: 5,
  },
  {
    id: "q-bc-1-6",
    lessonId: "biochemistry-1",
    text: "尿素回路について正しいのはどれか。",
    options: [
      { id: "a", text: "尿素回路は腎臓でのみ行われる" },
      { id: "b", text: "尿素回路の律速酵素はカルバモイルリン酸シンテターゼI（CPS-I）である" },
      { id: "c", text: "尿素1分子には窒素原子が1個含まれる" },
      { id: "d", text: "尿素回路はすべてミトコンドリア内で完結する" },
    ],
    correctOptionId: "b",
    explanation:
      "尿素回路（オルニチン回路）は主に肝臓で行われ、アミノ酸代謝で生じた有毒なアンモニア（NH₃）を無毒な尿素に変換する経路である。律速酵素はミトコンドリアマトリックスに存在するカルバモイルリン酸シンテターゼI（CPS-I）で、N-アセチルグルタミン酸（NAG）によりアロステリックに活性化される。尿素1分子にはNH₃由来とアスパラギン酸由来の計2個の窒素原子が含まれる（H₂N-CO-NH₂）。回路の前半2反応（CPS-I、オルニチントランスカルバモイラーゼ）はミトコンドリアで、後半3反応（アルギニノコハク酸シンテターゼ、アルギニノコハク酸リアーゼ、アルギナーゼ）は細胞質で進行する。尿素回路の先天的酵素欠損は高アンモニア血症を引き起こす。",
    subject: "生化学",
    order: 6,
  },
  {
    id: "q-bc-1-7",
    lessonId: "biochemistry-1",
    text: "ビタミンB₁（チアミン）欠乏で生じる疾患として正しいのはどれか。",
    options: [
      { id: "a", text: "壊血病" },
      { id: "b", text: "ウェルニッケ脳症" },
      { id: "c", text: "ペラグラ" },
      { id: "d", text: "巨赤芽球性貧血" },
    ],
    correctOptionId: "b",
    explanation:
      "ビタミンB₁（チアミン）はチアミンピロリン酸（TPP）として、ピルビン酸デヒドロゲナーゼ複合体・α-ケトグルタル酸デヒドロゲナーゼ複合体・分枝鎖α-ケトアシドデヒドロゲナーゼ・トランスケトラーゼの補酵素として機能する。チアミン欠乏ではこれらの酵素活性が低下し、特に脳のエネルギー代謝が障害される。ウェルニッケ脳症は眼球運動障害・運動失調・意識障害の三徴を呈し、慢性アルコール依存症患者に多い。進行するとコルサコフ症候群（逆向性健忘・作話）に移行する。壊血病はビタミンC欠乏、ペラグラはナイアシン（ビタミンB₃）欠乏、巨赤芽球性貧血はビタミンB₁₂または葉酸欠乏で生じる。",
    subject: "生化学",
    order: 7,
  },
  {
    id: "q-bc-1-8",
    lessonId: "biochemistry-1",
    text: "ミカエリス-メンテン式における Km（ミカエリス定数）の意味として正しいのはどれか。",
    options: [
      { id: "a", text: "反応速度が最大速度（Vmax）に達するときの基質濃度" },
      { id: "b", text: "反応速度が Vmax の 1/2 となるときの基質濃度" },
      { id: "c", text: "酵素と基質の結合定数そのもの" },
      { id: "d", text: "基質濃度にかかわらず一定の反応速度を示す値" },
    ],
    correctOptionId: "b",
    explanation:
      "ミカエリス-メンテン式は v = Vmax[S]/(Km + [S]) で表される。Km は反応速度が最大速度 Vmax の半分（Vmax/2）になるときの基質濃度[S]であり、酵素と基質の親和性の指標となる。Km が小さいほど低い基質濃度で Vmax/2 に達するため、酵素-基質間の親和性が高いことを意味する。Vmax は酵素が基質で完全に飽和したときの最大反応速度で、酵素濃度に比例する。競合阻害では見かけの Km が増大し Vmax は変わらない。非競合阻害では Km は変わらず Vmax が低下する。Lineweaver-Burk プロット（二重逆数プロット：1/v vs 1/[S]）により Km と Vmax を求めることができる。",
    subject: "生化学",
    order: 8,
  },
  // ── Lesson 2: 核酸とタンパク質合成 ───────────────────────────────────────────
  {
    id: "q-bc-2-1",
    lessonId: "biochemistry-2",
    text: "DNA複製において鋳型鎖を5'→3'方向に連続的に合成する鎖はどれか。",
    options: [
      { id: "a", text: "ラギング鎖" },
      { id: "b", text: "リーディング鎖" },
      { id: "c", text: "テロメア" },
      { id: "d", text: "オキザキフラグメント" },
    ],
    correctOptionId: "b",
    explanation: "リーディング鎖は複製フォーク方向に連続的に5'→3'で合成される。ラギング鎖はオキザキフラグメントを逆向きに合成し、後に連結される。",
    subject: "生化学",
    order: 1,
  },
  {
    id: "q-bc-2-2",
    lessonId: "biochemistry-2",
    text: "転写（mRNA合成）を触媒する酵素はどれか。",
    options: [
      { id: "a", text: "DNAポリメラーゼ" },
      { id: "b", text: "RNAポリメラーゼII" },
      { id: "c", text: "リボソーム" },
      { id: "d", text: "リガーゼ" },
    ],
    correctOptionId: "b",
    explanation: "真核生物ではRNAポリメラーゼIIがmRNA前駆体を合成する。DNAポリメラーゼは複製、リボソームは翻訳の場である。",
    subject: "生化学",
    order: 2,
  },
  {
    id: "q-bc-2-3",
    lessonId: "biochemistry-2",
    text: "コドンAUGがコードするアミノ酸はどれか。",
    options: [
      { id: "a", text: "グリシン" },
      { id: "b", text: "メチオニン（開始コドンとしても機能）" },
      { id: "c", text: "トリプトファン" },
      { id: "d", text: "チロシン" },
    ],
    correctOptionId: "b",
    explanation: "AUGはメチオニンをコードし、真核生物では開始コドンとしても機能する。",
    subject: "生化学",
    order: 3,
  },
  // ── Lesson 3: ビタミン・補酵素 ─────────────────────────────────────────────
  {
    id: "q-bc-3-1",
    lessonId: "biochemistry-3",
    text: "ナイアシン（ニコチン酸）が構成成分となる補酵素はどれか。",
    options: [
      { id: "a", text: "FAD" },
      { id: "b", text: "NAD⁺（ニコチンアミドアデニンジヌクレオチド）" },
      { id: "c", text: "CoA" },
      { id: "d", text: "チアミンピロリン酸" },
    ],
    correctOptionId: "b",
    explanation: "ナイアシンはNAD⁺・NADP⁺の構成成分。酸化還元反応で電子伝達体として働く。欠乏でペラグラをきたす。",
    subject: "生化学",
    order: 1,
  },
  {
    id: "q-bc-3-2",
    lessonId: "biochemistry-3",
    text: "ビタミンB1（チアミン）欠乏で起こる疾患はどれか。",
    options: [
      { id: "a", text: "壊血病" },
      { id: "b", text: "脚気・Wernicke脳症" },
      { id: "c", text: "夜盲症" },
      { id: "d", text: "悪性貧血" },
    ],
    correctOptionId: "b",
    explanation: "チアミンはピルビン酸デヒドロゲナーゼなどの補酵素。欠乏で脚気、Wernicke脳症（眼球運動障害・失調・意識障害）をきたす。",
    subject: "生化学",
    order: 2,
  },
  {
    id: "q-bc-3-3",
    lessonId: "biochemistry-3",
    text: "葉酸欠乏で障害されやすい代謝経路はどれか。",
    options: [
      { id: "a", text: "解糖系" },
      { id: "b", text: "プリン・ピリミジン合成、一炭素代謝（巨赤芽球性貧血の原因）" },
      { id: "c", text: "β酸化" },
      { id: "d", text: "糖新生" },
    ],
    correctOptionId: "b",
    explanation: "葉酸はテトラヒドロ葉酸として一炭素単位の転移に関与し、DNA合成に必要。欠乏で巨赤芽球性貧血。妊娠期の不足は神経管閉鎖障害のリスクを高める。",
    subject: "生化学",
    order: 3,
  },
];

export const biochemistryLessons: Lesson[] = [
  {
    id: "biochemistry-1",
    title: "生化学 — 代謝と酵素",
    questionIds: [
      "q-bc-1-1", "q-bc-1-2", "q-bc-1-3", "q-bc-1-4",
      "q-bc-1-5", "q-bc-1-6", "q-bc-1-7", "q-bc-1-8",
    ],
    subject: "生化学",
    examTag: "医師国家試験",
    order: 2,
    orderInSubject: 1,
    level: 1,
  },
  {
    id: "biochemistry-2",
    title: "生化学 — 核酸とタンパク質合成",
    questionIds: ["q-bc-2-1", "q-bc-2-2", "q-bc-2-3"],
    subject: "生化学",
    examTag: "医師国家試験",
    order: 3,
    orderInSubject: 2,
    level: 2,
  },
  {
    id: "biochemistry-3",
    title: "生化学 — ビタミン・補酵素",
    questionIds: ["q-bc-3-1", "q-bc-3-2", "q-bc-3-3"],
    subject: "生化学",
    examTag: "医師国家試験",
    order: 4,
    orderInSubject: 3,
    level: 3,
  },
];
