import type { Question, Lesson } from "@/types";

/** 免疫学 — 難易度順に orderInSubject を 1, 2, 3... で並べる */
export const immunologyQuestions: Question[] = [
  {
    id: "q-immuno-1",
    lessonId: "immunology-1",
    text: "液性免疫を担う主な細胞はどれか。",
    options: [
      { id: "a", text: "B細胞" },
      { id: "b", text: "T細胞" },
      { id: "c", text: "NK細胞" },
      { id: "d", text: "マクロファージ" },
    ],
    correctOptionId: "a",
    explanation: "B細胞は抗体を産生し、液性免疫を担う。T細胞は細胞性免疫を担う。",
    subject: "免疫学",
    order: 1,
  },
  // ── Lesson 2: 抗体・補体 ───────────────────────────────────────────────────
  {
    id: "q-immuno-2-1",
    lessonId: "immunology-2",
    text: "IgGの特徴として正しいのはどれか。",
    options: [
      { id: "a", text: "分子量が最大で、胎盤通過能はない" },
      { id: "b", text: "血中で最も多く、胎盤を通過し胎児を守る" },
      { id: "c", text: "主に粘膜で分泌型として働く" },
      { id: "d", text: "アレルギー即時型反応の主体" },
    ],
    correctOptionId: "b",
    explanation: "IgGは血中で最多の抗体。胎盤通過能があり新生児の受動免疫に寄与。IgAは粘膜、IgEはI型アレルギー、IgMは最大で初期免疫に多い。",
    subject: "免疫学",
    order: 1,
  },
  {
    id: "q-immuno-2-2",
    lessonId: "immunology-2",
    text: "補体の古典経路を活性化するのはどれか。",
    options: [
      { id: "a", text: "抗原のみ" },
      { id: "b", text: "IgGまたはIgMと抗原の複合体（C1qの結合）" },
      { id: "c", text: "マンノース結合レクチンのみ" },
      { id: "d", text: "インターロイキン" },
    ],
    correctOptionId: "b",
    explanation: "古典経路は抗原・抗体複合体にC1qが結合して始まる。別経路（Alternative）は菌体表面、レクチン経路はマンノースなどで活性化。",
    subject: "免疫学",
    order: 2,
  },
  {
    id: "q-immuno-2-3",
    lessonId: "immunology-2",
    text: "抗体の可変部（V領域）が主に担う機能はどれか。",
    options: [
      { id: "a", text: "補体の活性化" },
      { id: "b", text: "抗原認識（特異的結合）" },
      { id: "c", text: "Fc受容体への結合" },
      { id: "d", text: "血中半減期の決定" },
    ],
    correctOptionId: "b",
    explanation: "可変部（VH・VL）は抗原との特異的結合を担う。定常部（Fc）が補体結合・Fc受容体結合・胎盤通過などを担う。",
    subject: "免疫学",
    order: 3,
  },
  // ── Lesson 3: アレルギー・自己免疫 ─────────────────────────────────────────
  {
    id: "q-immuno-3-1",
    lessonId: "immunology-3",
    text: "I型（即時型）アレルギーで主に放出されるメディエーターはどれか。",
    options: [
      { id: "a", text: "インターフェロン" },
      { id: "b", text: "ヒスタミン（肥満細胞・好塩基球から）" },
      { id: "c", text: "TNF-α" },
      { id: "d", text: "インターロイキン-2" },
    ],
    correctOptionId: "b",
    explanation: "I型はIgEが肥満細胞などに結合し、抗原再曝露で脱顆粒しヒスタミン・ロイコトリエンなどを放出。蕁麻疹・喘息・アナフィラキシーの原因。",
    subject: "免疫学",
    order: 1,
  },
  {
    id: "q-immuno-3-2",
    lessonId: "immunology-3",
    text: "自己免疫疾患の例として適切なのはどれか。",
    options: [
      { id: "a", text: "感冒" },
      { id: "b", text: "全身性エリテマトーデス（SLE）・関節リウマチ" },
      { id: "c", text: "結核" },
      { id: "d", text: "マラリア" },
    ],
    correctOptionId: "b",
    explanation: "SLEは抗核抗体など、関節リウマチは抗CCP抗体などが関与する自己免疫疾患。自己抗原に対する免疫応答の異常が病態基盤。",
    subject: "免疫学",
    order: 2,
  },
  {
    id: "q-immuno-3-3",
    lessonId: "immunology-3",
    text: "遅延型（IV型）アレルギーを主に担う細胞はどれか。",
    options: [
      { id: "a", text: "B細胞" },
      { id: "b", text: "好中球" },
      { id: "c", text: "T細胞（Th1など）とマクロファージ" },
      { id: "d", text: "肥満細胞" },
    ],
    correctOptionId: "c",
    explanation: "IV型は感作T細胞が抗原と再会し、サイトカイン放出でマクロファージを動員。ツベルクリン反応・接触皮膚炎・移植拒絶など。",
    subject: "免疫学",
    order: 3,
  },
];

export const immunologyLessons: Lesson[] = [
  {
    id: "immunology-1",
    title: "免疫学 序論",
    questionIds: ["q-immuno-1"],
    subject: "免疫学",
    examTag: "医師国家試験",
    order: 1,
    orderInSubject: 1,
    level: 1,
  },
  {
    id: "immunology-2",
    title: "免疫学 — 抗体・補体",
    questionIds: ["q-immuno-2-1", "q-immuno-2-2", "q-immuno-2-3"],
    subject: "免疫学",
    examTag: "医師国家試験",
    order: 2,
    orderInSubject: 2,
    level: 2,
  },
  {
    id: "immunology-3",
    title: "免疫学 — アレルギー・自己免疫",
    questionIds: ["q-immuno-3-1", "q-immuno-3-2", "q-immuno-3-3"],
    subject: "免疫学",
    examTag: "医師国家試験",
    order: 3,
    orderInSubject: 3,
    level: 3,
  },
];
