import type { Question, Lesson } from "@/types";

/** 医療倫理 — 難易度順に orderInSubject を 1, 2, 3... で並べる */
export const medicalEthicsQuestions: Question[] = [
  {
    id: "q-ethics-1",
    lessonId: "medical-ethics-1",
    text: "医療における「インフォームド・コンセント」で最も重要な要素はどれか。",
    options: [
      { id: "a", text: "医師の専門的判断の説明" },
      { id: "b", text: "患者の理解に基づく同意" },
      { id: "c", text: "家族の同意" },
      { id: "d", text: "診療録への記載" },
    ],
    correctOptionId: "b",
    explanation: "インフォームド・コンセントは、十分な説明を受けた上で患者が理解し、自発的に同意することが本質である。",
    subject: "医療倫理",
    order: 1,
  },
  // ── Lesson 2: 倫理原則・患者の権利 ─────────────────────────────────────
  {
    id: "q-ethics-2-1",
    lessonId: "medical-ethics-2",
    text: "医療倫理の四原則に含まれないのはどれか。",
    options: [
      { id: "a", text: "自律尊重（autonomy）" },
      { id: "b", text: "善行（beneficence）" },
      { id: "c", text: "正義（justice）" },
      { id: "d", text: "効率性（efficiency）" },
    ],
    correctOptionId: "d",
    explanation: "ビーチャンプの四原則は自律尊重・善行・危害を与えないこと（non-maleficence）・正義。効率性は原則には含まれない。",
    subject: "医療倫理",
    order: 1,
  },
  {
    id: "q-ethics-2-2",
    lessonId: "medical-ethics-2",
    text: "患者の「知情同意」において特に重視されるのはどれか。",
    options: [
      { id: "a", text: "医師の効率" },
      { id: "b", text: "患者の理解と自発的な同意" },
      { id: "c", text: "家族の意向のみ" },
      { id: "d", text: "診療録の簡潔さ" },
    ],
    correctOptionId: "b",
    explanation: "知情同意は、病状・治療内容・リスク・代替案について説明を受け、理解した上で患者が自発的に同意することを重視する。",
    subject: "医療倫理",
    order: 2,
  },
  {
    id: "q-ethics-2-3",
    lessonId: "medical-ethics-2",
    text: "医療における「守秘義務」の例外として認められうるのはどれか。",
    options: [
      { id: "a", text: "患者の許可なく第三者に趣味を話すこと" },
      { id: "b", text: "法令に基づく届出（感染症法・児童虐待など）や患者・第三者の重大な危害の回避" },
      { id: "c", text: "診療と無関係な私的な会話" },
      { id: "d", text: "利益のためであれば開示してよい" },
    ],
    correctOptionId: "b",
    explanation: "守秘義務は原則だが、感染症法・児童虐待防止法など法令上の届出義務、患者・他人の生命身体の重大な危害の回避など、例外的に開示が認められる場合がある。",
    subject: "医療倫理",
    order: 3,
  },
  // ── Lesson 3: 終末期・研究倫理 ─────────────────────────────────────────
  {
    id: "q-ethics-3-1",
    lessonId: "medical-ethics-3",
    text: "終末期医療で「尊厳死」の考え方として適切なのはどれか。",
    options: [
      { id: "a", text: "積極的な致死行為（安楽死）と同一である" },
      { id: "b", text: "過剰な延命措置を差し控え、自然な死を迎えることを尊重する" },
      { id: "c", text: "患者の意思確認は不要である" },
      { id: "d", text: "苦痛の除去は認められない" },
    ],
    correctOptionId: "b",
    explanation: "尊厳死は、回復見込みのない終末期に過剰な延命を行わず、患者の意思やQOLを尊重して自然な死を迎えることを指す。安楽死（積極的致死）とは区別される。",
    subject: "医療倫理",
    order: 1,
  },
  {
    id: "q-ethics-3-2",
    lessonId: "medical-ethics-3",
    text: "治験・研究における倫理で重要なのはどれか。",
    options: [
      { id: "a", text: "被験者・患者の同意は不要である" },
      { id: "b", text: "インフォームド・コンセント・利益とリスクの評価・倫理審査委員会の審査" },
      { id: "c", text: "研究の効率のみを優先する" },
      { id: "d", text: "結果の開示は不要である" },
    ],
    correctOptionId: "b",
    explanation: "人を対象とする研究では、十分な説明と自発的同意（IC）、リスク・利益の評価、倫理審査委員会の承認が求められる。ヘルシンキ宣言などが指針となる。",
    subject: "医療倫理",
    order: 2,
  },
  {
    id: "q-ethics-3-3",
    lessonId: "medical-ethics-3",
    text: "アドバンス・ケア・プラニング（ACP）の目的として適切なのはどれか。",
    options: [
      { id: "a", text: "医療費の削減のみ" },
      { id: "b", text: "将来の意思決定能力低下に備え、本人の価値観や希望に基づく医療・ケアについて事前に話し合う" },
      { id: "c", text: "家族の意向のみを記録する" },
      { id: "d", text: "延命治療の一律拒否を目的とする" },
    ],
    correctOptionId: "b",
    explanation: "ACPは、本人が意思表示できるうちに、将来の医療・ケアの希望や価値観を話し合い、記録・共有するプロセス。本人の自律と尊厳を支える。",
    subject: "医療倫理",
    order: 3,
  },
];

export const medicalEthicsLessons: Lesson[] = [
  {
    id: "medical-ethics-1",
    title: "医療倫理 序論",
    questionIds: ["q-ethics-1"],
    subject: "医療倫理",
    examTag: "医師国家試験",
    order: 1,
    orderInSubject: 1,
    level: 1,
  },
  {
    id: "medical-ethics-2",
    title: "医療倫理 — 倫理原則・患者の権利",
    questionIds: ["q-ethics-2-1", "q-ethics-2-2", "q-ethics-2-3"],
    subject: "医療倫理",
    examTag: "医師国家試験",
    order: 2,
    orderInSubject: 2,
    level: 2,
  },
  {
    id: "medical-ethics-3",
    title: "医療倫理 — 終末期・研究倫理",
    questionIds: ["q-ethics-3-1", "q-ethics-3-2", "q-ethics-3-3"],
    subject: "医療倫理",
    examTag: "医師国家試験",
    order: 3,
    orderInSubject: 3,
    level: 3,
  },
];
