import type { Question, Lesson } from "@/types";

/** 微生物学総論 — 感染と防御（8問・1レッスン） */
export const microbiologyQuestions: Question[] = [
  // ── Lesson 1: 微生物学総論 — 感染と防御 ─────────────────────────────────────
  {
    id: "q-mi-1-1",
    lessonId: "microbiology-1",
    text: "グラム陰性菌の細胞壁の特徴として正しいのはどれか。",
    options: [
      { id: "a", text: "ペプチドグリカン層が厚く、タイコ酸を含む" },
      { id: "b", text: "ペプチドグリカン層が薄く、外膜にリポ多糖（LPS）を有する" },
      { id: "c", text: "細胞壁を欠き、ステロールを含む細胞膜で覆われている" },
      { id: "d", text: "ペプチドグリカンを全く持たず、外膜のみで構成される" },
    ],
    correctOptionId: "b",
    explanation:
      "グラム陰性菌はペプチドグリカン層が薄く（1〜2層）、その外側に外膜（outer membrane）を持つ。外膜にはリポ多糖（LPS: lipopolysaccharide）が存在し、エンドトキシンとして作用する。LPSのリピドA部分が毒性の本体であり、敗血症性ショック（エンドトキシンショック）の原因となる。一方、グラム陽性菌はペプチドグリカン層が厚く（20〜80層）、タイコ酸・リポタイコ酸を含むが外膜は持たない。細胞壁を欠くのはマイコプラズマの特徴である。",
    subject: "微生物学総論",
    order: 1,
  },
  {
    id: "q-mi-1-2",
    lessonId: "microbiology-1",
    text: "芽胞形成菌の組み合わせとして正しいのはどれか。",
    options: [
      { id: "a", text: "黄色ブドウ球菌・大腸菌・緑膿菌・肺炎球菌" },
      { id: "b", text: "破傷風菌・ボツリヌス菌・ウェルシュ菌・炭疽菌" },
      { id: "c", text: "結核菌・らい菌・ジフテリア菌・百日咳菌" },
      { id: "d", text: "コレラ菌・赤痢菌・チフス菌・サルモネラ菌" },
    ],
    correctOptionId: "b",
    explanation:
      "芽胞（endospore）を形成する代表的な細菌は、Clostridium属（破傷風菌 C. tetani、ボツリヌス菌 C. botulinum、ウェルシュ菌 C. perfringens、ディフィシル菌 C. difficile）およびBacillus属（炭疽菌 B. anthracis、セレウス菌 B. cereus）である。芽胞は熱・乾燥・消毒薬・紫外線に高い抵抗性を示し、通常の煮沸消毒（100℃）では死滅しない。滅菌にはオートクレーブ（121℃・2気圧・15〜20分）が必要である。",
    subject: "微生物学総論",
    order: 2,
  },
  {
    id: "q-mi-1-3",
    lessonId: "microbiology-1",
    text: "芽胞を含む器具の滅菌法として最も適切なのはどれか。",
    options: [
      { id: "a", text: "70%エタノールによる消毒" },
      { id: "b", text: "オートクレーブ（高圧蒸気滅菌：121℃・2気圧・15〜20分）" },
      { id: "c", text: "流通蒸気法（100℃・30分）" },
      { id: "d", text: "逆性石鹸（塩化ベンザルコニウム）による浸漬" },
    ],
    correctOptionId: "b",
    explanation:
      "オートクレーブ（高圧蒸気滅菌）は121℃・2気圧・15〜20分の条件で芽胞を含むすべての微生物を死滅させる最も確実な滅菌法である。耐熱性の器具・培地・リネン類に適用される。EOG（酸化エチレンガス）滅菌は熱に弱いプラスチック・光学機器に用いる。乾熱滅菌（160〜170℃・1〜2時間）はガラス器具・金属に適する。濾過滅菌（メンブレンフィルター 0.22μm）は熱に弱い液体（血清・抗生物質溶液）に用いる。70%エタノールや逆性石鹸は消毒であり、芽胞には無効である。",
    subject: "微生物学総論",
    order: 3,
  },
  {
    id: "q-mi-1-4",
    lessonId: "microbiology-1",
    text: "コッホの4原則に含まれないのはどれか。",
    options: [
      { id: "a", text: "ある疾患の患者から特定の微生物が常に検出されること" },
      { id: "b", text: "その微生物を純培養で分離できること" },
      { id: "c", text: "純培養した微生物を感受性動物に接種すると同じ疾患が再現されること" },
      { id: "d", text: "その微生物に対するワクチンが開発されていること" },
    ],
    correctOptionId: "d",
    explanation:
      "コッホの4原則（Koch's postulates）は感染症の病原体を特定するための基準である。①ある疾患の患者から特定の微生物が常に検出される、②その微生物を純培養で分離できる、③純培養した微生物を感受性動物に接種すると同じ疾患が再現される、④その動物から再び同じ微生物が分離される。ワクチンの有無は原則に含まれない。なお、ウイルスや培養困難な微生物（らい菌・梅毒トレポネーマなど）にはこの原則を厳密に適用できない場合がある。",
    subject: "微生物学総論",
    order: 4,
  },
  {
    id: "q-mi-1-5",
    lessonId: "microbiology-1",
    text: "常在細菌叢（正常フローラ）の役割として誤っているのはどれか。",
    options: [
      { id: "a", text: "病原微生物の定着を阻害する（定着阻止）" },
      { id: "b", text: "ビタミンK・ビタミンB群の産生に関与する" },
      { id: "c", text: "腸管免疫の発達・成熟を促進する" },
      { id: "d", text: "宿主のすべての感染症を完全に予防する" },
    ],
    correctOptionId: "d",
    explanation:
      "常在細菌叢（正常フローラ）は①定着阻止（colonization resistance）：栄養・付着部位の競合や抗菌物質（バクテリオシン）の産生により病原菌の定着を抑制、②ビタミン産生：大腸の細菌がビタミンK・ビタミンB12・葉酸などを合成、③免疫系の成熟：腸管関連リンパ組織（GALT）の発達を促進しIgA産生を誘導する。ただし、フローラは万能ではなく、免疫不全時には常在菌自体が日和見感染の原因となる。抗菌薬の長期投与でフローラが破壊されると、Clostridioides difficile感染症（偽膜性腸炎）などの菌交代症が生じる。",
    subject: "微生物学総論",
    order: 5,
  },
  {
    id: "q-mi-1-6",
    lessonId: "microbiology-1",
    text: "日和見感染の説明として正しいのはどれか。",
    options: [
      { id: "a", text: "健常者に強い病原性を示す微生物による感染症である" },
      { id: "b", text: "免疫機能が低下した宿主において、通常は非病原性の微生物が感染症を引き起こすことである" },
      { id: "c", text: "特定の地域にのみ発生する風土病のことである" },
      { id: "d", text: "外毒素を産生する細菌のみが原因となる感染症である" },
    ],
    correctOptionId: "b",
    explanation:
      "日和見感染（opportunistic infection）は、免疫機能が低下した宿主（AIDS患者、抗癌剤投与中、臓器移植後の免疫抑制剤使用者、糖尿病患者など）において、通常は病原性の低い微生物が感染症を引き起こす状態をいう。代表的な原因微生物には、ニューモシスチス・イロベチイ（Pneumocystis jirovecii：カリニ肺炎）、カンジダ属（口腔・食道カンジダ症）、アスペルギルス属（侵襲性肺アスペルギルス症）、サイトメガロウイルス（CMV）、緑膿菌、MRSA（メチシリン耐性黄色ブドウ球菌）などがある。",
    subject: "微生物学総論",
    order: 6,
  },
  {
    id: "q-mi-1-7",
    lessonId: "microbiology-1",
    text: "空気感染（飛沫核感染）する疾患の組み合わせとして正しいのはどれか。",
    options: [
      { id: "a", text: "結核・麻疹・水痘" },
      { id: "b", text: "インフルエンザ・風疹・ムンプス" },
      { id: "c", text: "コレラ・赤痢・A型肝炎" },
      { id: "d", text: "マラリア・デング熱・日本脳炎" },
    ],
    correctOptionId: "a",
    explanation:
      "空気感染（飛沫核感染：airborne transmission）は、飛沫核（5μm以下の微粒子）が長時間空中に浮遊し、遠方まで到達して感染を成立させる。代表的な疾患は結核・麻疹・水痘の3疾患である（覚え方：「けま水」「空気感染は\"まけみず\"」）。これらの患者は陰圧個室での隔離とN95マスクの着用が必要となる。インフルエンザ・風疹・ムンプスは飛沫感染（droplet）、コレラ・赤痢・A型肝炎は経口感染（fecal-oral）、マラリア・デング熱・日本脳炎は蚊（ベクター）媒介感染である。",
    subject: "微生物学総論",
    order: 7,
  },
  {
    id: "q-mi-1-8",
    lessonId: "microbiology-1",
    text: "バイオフィルムについて正しいのはどれか。",
    options: [
      { id: "a", text: "バイオフィルム内の細菌は浮遊細菌よりも抗菌薬感受性が高い" },
      { id: "b", text: "バイオフィルムは細菌が産生する多糖体・タンパク質・DNAからなる細胞外マトリックスに包まれた構造体である" },
      { id: "c", text: "バイオフィルムはガラスや金属表面には形成されない" },
      { id: "d", text: "バイオフィルム感染症は抗菌薬のみで容易に治療できる" },
    ],
    correctOptionId: "b",
    explanation:
      "バイオフィルム（biofilm）は、細菌が固体表面に付着し、自ら産生する細胞外多糖体（EPS: extracellular polymeric substances）・タンパク質・細胞外DNAからなるマトリックスに包まれて形成する構造体である。バイオフィルム内の細菌は浮遊状態の細菌に比べ、抗菌薬や宿主免疫から保護されるため、10〜1000倍の薬剤耐性を示す。臨床的には、人工関節・心臓弁膜症の人工弁・尿道カテーテル・中心静脈カテーテルなどの医療デバイス関連感染の主要原因となる。治療には感染デバイスの除去（抜去・交換）が必要となることが多く、抗菌薬単独での根治は困難である。",
    subject: "微生物学総論",
    order: 8,
  },
  // ── Lesson 2: 消毒・滅菌・感染経路 ───────────────────────────────────────
  {
    id: "q-mi-2-1",
    lessonId: "microbiology-2",
    text: "高レベル消毒が可能な消毒薬はどれか。",
    options: [
      { id: "a", text: "70%エタノール" },
      { id: "b", text: "グルタラール・次亜塩素酸ナトリウム（適切な濃度・接触時間で芽胞にも有効）" },
      { id: "c", text: "逆性石鹸のみ" },
      { id: "d", text: "クロルヘキシジンのみ" },
    ],
    correctOptionId: "b",
    explanation: "高レベル消毒は芽胞を除くほぼすべての微生物を不活化。グルタラール・フタラール・次亜塩素酸など。中レベルは結核菌・多くのウイルス、低レベルは細菌繁殖体・一部ウイルス。",
    subject: "微生物学総論",
    order: 1,
  },
  {
    id: "q-mi-2-2",
    lessonId: "microbiology-2",
    text: "飛沫感染する病原体の例として正しいのはどれか。",
    options: [
      { id: "a", text: "結核菌（主に空気感染）" },
      { id: "b", text: "インフルエンザウイルス・マイコプラズマ" },
      { id: "c", text: "B型肝炎ウイルス（血液媒介）" },
      { id: "d", text: "コレラ菌（経口感染）" },
    ],
    correctOptionId: "b",
    explanation: "飛沫感染は咳・くしゃみで飛んだ5μm以上の飛沫で伝播。インフルエンザ・マイコプラズマ・百日咳など。空気感染は結核・麻疹、接触はMRSA、血液媒介はHBV・HCV・HIV。",
    subject: "微生物学総論",
    order: 2,
  },
  {
    id: "q-mi-2-3",
    lessonId: "microbiology-2",
    text: "標準予防策（スタンダードプリコーション）で基本となるのはどれか。",
    options: [
      { id: "a", text: "血液・体液はすべて感染性があるとみなす" },
      { id: "b", text: "咳のある患者にのみ手袋を使用する" },
      { id: "c", text: "使い捨て器材は再使用してよい" },
      { id: "d", text: "手洗いは患者接触後のみ行う" },
    ],
    correctOptionId: "a",
    explanation: "標準予防策ではすべての患者の血液・体液・分泌物・排泄物・傷のある皮膚・粘膜を感染性ありとみなし、手洗い・手袋・ガウン・マスク等を状況に応じて使用する。",
    subject: "微生物学総論",
    order: 3,
  },
  // ── Lesson 3: 耐性菌・院内感染 ───────────────────────────────────────────
  {
    id: "q-mi-3-1",
    lessonId: "microbiology-3",
    text: "MRSAの「M」が示す耐性はどれか。",
    options: [
      { id: "a", text: "マクロライド" },
      { id: "b", text: "メトロニダゾール" },
      { id: "c", text: "メチシリン（βラクタム系）" },
      { id: "d", text: "ミノサイクリン" },
    ],
    correctOptionId: "c",
    explanation: "MRSAはMethicillin-resistant Staphylococcus aureus（メチシリン耐性黄色ブドウ球菌）。PBP2aを産生しβラクタム系に耐性。バンコマイシンなどが治療に用いられる。",
    subject: "微生物学総論",
    order: 1,
  },
  {
    id: "q-mi-3-2",
    lessonId: "microbiology-3",
    text: "ESBL産生菌の特徴として正しいのはどれか。",
    options: [
      { id: "a", text: "ペニシリン系のみ分解する" },
      { id: "b", text: "extended spectrum β-lactamase により第三世代セフェムなど多くのβラクタム系に耐性" },
      { id: "c", text: "カルバペネムに耐性である" },
      { id: "d", text: "グラム陽性菌のみ" },
    ],
    correctOptionId: "b",
    explanation: "ESBLは基質拡張型βラクタマーゼで、第三世代セフェムなどを分解。多くはカルバペネムには感受性。大腸菌・ Klebsiella などグラム陰性桿菌で問題となる。",
    subject: "微生物学総論",
    order: 2,
  },
  {
    id: "q-mi-3-3",
    lessonId: "microbiology-3",
    text: "カテーテル関連血流感染の予防で正しいのはどれか。",
    options: [
      { id: "a", text: "挿入部位は鼠径部が最適である" },
      { id: "b", text: "無菌操作・適切な挿入部位（鎖骨下静脈など）・不要時は早期抜去" },
      { id: "c", text: "カテーテルは可能な限り長期留置する" },
      { id: "d", text: "消毒は不要である" },
    ],
    correctOptionId: "b",
    explanation: "挿入は無菌的に、鎖骨下静脈など感染リスクの低い部位を選ぶ。必要性を定期的に評価し不要なら抜去。挿入部のケア・ハンドハイジーンも重要。",
    subject: "微生物学総論",
    order: 3,
  },
];

export const microbiologyLessons: Lesson[] = [
  {
    id: "microbiology-1",
    title: "微生物学総論 — 感染と防御",
    questionIds: [
      "q-mi-1-1", "q-mi-1-2", "q-mi-1-3", "q-mi-1-4",
      "q-mi-1-5", "q-mi-1-6", "q-mi-1-7", "q-mi-1-8",
    ],
    subject: "微生物学総論",
    examTag: "医師国家試験",
    order: 8,
    orderInSubject: 1,
    level: 1,
  },
  {
    id: "microbiology-2",
    title: "微生物学総論 — 消毒・滅菌・感染経路",
    questionIds: ["q-mi-2-1", "q-mi-2-2", "q-mi-2-3"],
    subject: "微生物学総論",
    examTag: "医師国家試験",
    order: 9,
    orderInSubject: 2,
    level: 2,
  },
  {
    id: "microbiology-3",
    title: "微生物学総論 — 耐性菌・院内感染",
    questionIds: ["q-mi-3-1", "q-mi-3-2", "q-mi-3-3"],
    subject: "微生物学総論",
    examTag: "医師国家試験",
    order: 10,
    orderInSubject: 3,
    level: 3,
  },
];
